services:
  - type: worker
    name: nagicorebot
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_IDS
        sync: false
      - key: BOT_NAME
        value: NagiCoreBot
      - key: MAX_DOWNLOAD_MB
        value: "50"
      - key: DOWNLOAD_TTL_MINUTES
        value: "10"
